// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp64EGR6nMbfMonQ7PFQMmFOQk8wC14XY',
    appId: '1:414162632829:web:b8ff721bc13b4dec13b114',
    messagingSenderId: '414162632829',
    projectId: 'wordlession',
    authDomain: 'wordlession.firebaseapp.com',
    databaseURL: 'https://wordlession-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wordlession.firebasestorage.app',
    measurementId: 'G-RWF3WSSB2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChUlD7fHw9M7-XrI9NBcqVLMM2bXit1U8',
    appId: '1:414162632829:android:947610d4788aae2713b114',
    messagingSenderId: '414162632829',
    projectId: 'wordlession',
    databaseURL: 'https://wordlession-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wordlession.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFrbwzlT76Vbv8abMzVGdqSwbi-AJJvo',
    appId: '1:414162632829:ios:ef7ae473a796539a13b114',
    messagingSenderId: '414162632829',
    projectId: 'wordlession',
    databaseURL: 'https://wordlession-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wordlession.firebasestorage.app',
    iosBundleId: 'com.example.wordLession',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSFrbwzlT76Vbv8abMzVGdqSwbi-AJJvo',
    appId: '1:414162632829:ios:ef7ae473a796539a13b114',
    messagingSenderId: '414162632829',
    projectId: 'wordlession',
    databaseURL: 'https://wordlession-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wordlession.firebasestorage.app',
    iosBundleId: 'com.example.wordLession',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp64EGR6nMbfMonQ7PFQMmFOQk8wC14XY',
    appId: '1:414162632829:web:b5ce05899c505f0313b114',
    messagingSenderId: '414162632829',
    projectId: 'wordlession',
    authDomain: 'wordlession.firebaseapp.com',
    databaseURL: 'https://wordlession-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wordlession.firebasestorage.app',
    measurementId: 'G-KM7LTLKXR2',
  );
}
